export const MAIN_ROUTE = '/'
export const SHOP_ROUTE = '/shop'
export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const CART_ROUTE = '/cart'
export const ITEM_ROUTE = '/item/:id?'
export const REGISTRATION_ROUTE = '/registration'
export const ERROR_ROUTE = '/error'
export const THANKYOU_ROUTE = '/thankyou'

export const currencyFormat = '$'
