export const MAIN_ROUTE = '/'
export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const CART_ROUTE = '/cart'
export const ITEM_ROUTE = '/item/:id?'
export const REGISTRATION_ROUTE = '/registration'
